// @generated by protoc-gen-es v1.8.0
// @generated from file google/services/health_rpc.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ServingStatus } from "../models/health_models_pb.js";

/**
 * @generated from message grpc.health.v1.HealthCheckRequest
 */
export declare class HealthCheckRequest extends Message<HealthCheckRequest> {
  /**
   * @generated from field: string service = 1;
   */
  service: string;

  constructor(data?: PartialMessage<HealthCheckRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grpc.health.v1.HealthCheckRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthCheckRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthCheckRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthCheckRequest;

  static equals(a: HealthCheckRequest | PlainMessage<HealthCheckRequest> | undefined, b: HealthCheckRequest | PlainMessage<HealthCheckRequest> | undefined): boolean;
}

/**
 * @generated from message grpc.health.v1.HealthCheckResponse
 */
export declare class HealthCheckResponse extends Message<HealthCheckResponse> {
  /**
   * @generated from field: grpc.health.v1.ServingStatus status = 1;
   */
  status: ServingStatus;

  constructor(data?: PartialMessage<HealthCheckResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grpc.health.v1.HealthCheckResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthCheckResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthCheckResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthCheckResponse;

  static equals(a: HealthCheckResponse | PlainMessage<HealthCheckResponse> | undefined, b: HealthCheckResponse | PlainMessage<HealthCheckResponse> | undefined): boolean;
}

