// @generated by protoc-gen-es v1.8.0
// @generated from file consensus/models/block_id.proto (package co.topl.consensus.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message co.topl.consensus.models.BlockId
 */
export declare class BlockId extends Message<BlockId> {
  /**
   * length = 32
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;

  constructor(data?: PartialMessage<BlockId>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.consensus.models.BlockId";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockId;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockId;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockId;

  static equals(a: BlockId | PlainMessage<BlockId> | undefined, b: BlockId | PlainMessage<BlockId> | undefined): boolean;
}

