// @generated by protoc-gen-es v1.8.0
// @generated from file consensus/models/block_header.proto (package co.topl.consensus.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { BlockId } from "./block_id_pb.js";
import { EligibilityCertificate } from "./eligibility_certificate_pb.js";
import { OperationalCertificate } from "./operational_certificate_pb.js";
import { StakingAddress } from "./staking_pb.js";
import { ProtocolVersion } from "./protocol_version_pb.js";

/**
 * Captures a block producer's consensus-commitment to a new block
 *
 * @generated from message co.topl.consensus.models.BlockHeader
 */
export const BlockHeader = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.consensus.models.BlockHeader",
  () => [
    { no: 12, name: "headerId", kind: "message", T: BlockId },
    { no: 1, name: "parentHeaderId", kind: "message", T: BlockId },
    { no: 2, name: "parentSlot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "txRoot", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "bloomFilter", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "eligibilityCertificate", kind: "message", T: EligibilityCertificate },
    { no: 9, name: "operationalCertificate", kind: "message", T: OperationalCertificate },
    { no: 10, name: "metadata", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 11, name: "address", kind: "message", T: StakingAddress },
    { no: 13, name: "version", kind: "message", T: ProtocolVersion },
  ],
);

