// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file consensus/models/eligibility_certificate.proto (package co.topl.consensus.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * A certificate proving the operator's election
 *
 * @generated from message co.topl.consensus.models.EligibilityCertificate
 */
export class EligibilityCertificate extends Message<EligibilityCertificate> {
  /**
   * Signs `eta ++ slot` using the `vrfSK`
   *
   * @generated from field: bytes vrfSig = 1;
   */
  vrfSig = new Uint8Array(0);

  /**
   * The VRF VK
   *
   * @generated from field: bytes vrfVK = 2;
   */
  vrfVK = new Uint8Array(0);

  /**
   * Hash of the operator's `threshold`
   * routine = blake2b256
   * length = 32
   *
   * @generated from field: bytes thresholdEvidence = 3;
   */
  thresholdEvidence = new Uint8Array(0);

  /**
   * The epoch's randomness
   * length = 32
   *
   * @generated from field: bytes eta = 4;
   */
  eta = new Uint8Array(0);

  constructor(data?: PartialMessage<EligibilityCertificate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "co.topl.consensus.models.EligibilityCertificate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vrfSig", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "vrfVK", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "thresholdEvidence", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "eta", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EligibilityCertificate {
    return new EligibilityCertificate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EligibilityCertificate {
    return new EligibilityCertificate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EligibilityCertificate {
    return new EligibilityCertificate().fromJsonString(jsonString, options);
  }

  static equals(a: EligibilityCertificate | PlainMessage<EligibilityCertificate> | undefined, b: EligibilityCertificate | PlainMessage<EligibilityCertificate> | undefined): boolean {
    return proto3.util.equals(EligibilityCertificate, a, b);
  }
}

