// @generated by protoc-gen-es v1.8.0
// @generated from file consensus/models/protocol_version.proto (package co.topl.consensus.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Protocol Version Specification, see TIP-003
 *
 * @generated from message co.topl.consensus.models.ProtocolVersion
 */
export const ProtocolVersion = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.consensus.models.ProtocolVersion",
  () => [
    { no: 1, name: "firstDigit", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "secondDigit", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "thirdDigit", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

