// @generated by protoc-gen-es v1.8.0
// @generated from file consensus/models/slot_data.proto (package co.topl.consensus.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { BlockId } from "./block_id_pb.js";

/**
 * Represents a "mini" block header, containing just a subset of its data needed to quickly inspect consensus characteristics of a block
 *
 * @generated from message co.topl.consensus.models.SlotData
 */
export const SlotData = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.consensus.models.SlotData",
  () => [
    { no: 1, name: "slotId", kind: "message", T: SlotId },
    { no: 2, name: "parentSlotId", kind: "message", T: SlotId },
    { no: 3, name: "rho", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "eta", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * A glorified tuple
 *
 * @generated from message co.topl.consensus.models.SlotId
 */
export const SlotId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.consensus.models.SlotId",
  () => [
    { no: 1, name: "slot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "blockId", kind: "message", T: BlockId },
  ],
);

