// @generated by protoc-gen-es v1.8.0
// @generated from file node/models/node_epochData.proto (package co.topl.proto.node, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Int128 } from "../../quivr/models/shared_pb.js";

/**
 * Epoch data Contains, The "current" epoch is updated as node blocks are adopted over time
 *
 * @generated from message co.topl.proto.node.EpochData
 */
export const EpochData = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.proto.node.EpochData",
  () => [
    { no: 1, name: "epoch", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "eon", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "era", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "isComplete", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "startHeight", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "endHeight", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "startSlot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "endSlot", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 9, name: "startTimestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 10, name: "endTimestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "transactionCount", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 12, name: "totalTransactionReward", kind: "message", T: Int128 },
    { no: 13, name: "activeStake", kind: "message", T: Int128 },
    { no: 14, name: "inactiveStake", kind: "message", T: Int128 },
    { no: 15, name: "dataBytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

