// @generated by protoc-gen-es v1.8.0
// @generated from file node/models/p2p.proto (package co.topl.node.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Request type for CurrentKnownHosts
 *
 * @generated from message co.topl.node.models.CurrentKnownHostsReq
 */
export const CurrentKnownHostsReq = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.node.models.CurrentKnownHostsReq",
  () => [
    { no: 1, name: "maxCount", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message co.topl.node.models.KnownHost
 */
export const KnownHost = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.node.models.KnownHost",
  () => [
    { no: 3, name: "id", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 1, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "port", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * Response type for CurrentKnownHosts
 *
 * @generated from message co.topl.node.models.CurrentKnownHostsRes
 */
export const CurrentKnownHostsRes = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.node.models.CurrentKnownHostsRes",
  () => [
    { no: 1, name: "hotHosts", kind: "message", T: KnownHost, repeated: true },
    { no: 2, name: "warmHosts", kind: "message", T: KnownHost, repeated: true },
    { no: 3, name: "coldHosts", kind: "message", T: KnownHost, repeated: true },
  ],
);

/**
 * @generated from message co.topl.node.models.PingMessage
 */
export const PingMessage = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.node.models.PingMessage",
  () => [
    { no: 1, name: "ping", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message co.topl.node.models.PongMessage
 */
export const PongMessage = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.node.models.PongMessage",
  () => [
    { no: 1, name: "pong", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

