// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file google/models/health_models.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum grpc.health.v1.ServingStatus
 */
export enum ServingStatus {
  /**
   * Default status. Indicates that no stats was returned.
   *
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * Service is in a healthy state.
   *
   * @generated from enum value: SERVING = 1;
   */
  SERVING = 1,

  /**
   * Service is unhealthy. Reason is implementation specific.
   *
   * @generated from enum value: NOT_SERVING = 2;
   */
  NOT_SERVING = 2,

  /**
   * Used only by the Watch method.
   *
   * @generated from enum value: SERVICE_UNKNOWN = 3;
   */
  SERVICE_UNKNOWN = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ServingStatus)
proto3.util.setEnumType(ServingStatus, "grpc.health.v1.ServingStatus", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "SERVING" },
  { no: 2, name: "NOT_SERVING" },
  { no: 3, name: "SERVICE_UNKNOWN" },
]);

