// @generated by protoc-gen-es v1.8.0
// @generated from file google/models/health_models.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum grpc.health.v1.ServingStatus
 */
export const ServingStatus = /*@__PURE__*/ proto3.makeEnum(
  "grpc.health.v1.ServingStatus",
  [
    {no: 0, name: "UNKNOWN"},
    {no: 1, name: "SERVING"},
    {no: 2, name: "NOT_SERVING"},
    {no: 3, name: "SERVICE_UNKNOWN"},
  ],
);

