// @generated by protoc-gen-es v1.8.0
// @generated from file google/models/health_models.proto (package grpc.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum grpc.health.v1.ServingStatus
 */
export declare enum ServingStatus {
  /**
   * Default status. Indicates that no stats was returned.
   *
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * Service is in a healthy state.
   *
   * @generated from enum value: SERVING = 1;
   */
  SERVING = 1,

  /**
   * Service is unhealthy. Reason is implementation specific.
   *
   * @generated from enum value: NOT_SERVING = 2;
   */
  NOT_SERVING = 2,

  /**
   * Used only by the Watch method.
   *
   * @generated from enum value: SERVICE_UNKNOWN = 3;
   */
  SERVICE_UNKNOWN = 3,
}

