// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/common.proto (package co.topl.brambl.models.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Immutable byte representation of a value
 *
 * @generated from message co.topl.brambl.models.common.ImmutableBytes
 */
export declare class ImmutableBytes extends Message<ImmutableBytes> {
  /**
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;

  constructor(data?: PartialMessage<ImmutableBytes>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.common.ImmutableBytes";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImmutableBytes;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImmutableBytes;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImmutableBytes;

  static equals(a: ImmutableBytes | PlainMessage<ImmutableBytes> | undefined, b: ImmutableBytes | PlainMessage<ImmutableBytes> | undefined): boolean;
}

