// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/identifier.proto (package co.topl.brambl.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Represents the identifier of a Transaction.  It is constructed from the evidence of the signable bytes of the Transaction.
 *
 * @generated from message co.topl.brambl.models.TransactionId
 */
export const TransactionId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.TransactionId",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * Represents the identifier of a Lock.  It is constructed from the evidence of the signable bytes of the Lock.
 *
 * @generated from message co.topl.brambl.models.LockId
 */
export const LockId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.LockId",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * Represents the identifier of an Accumulator Root.  It is constructed from the evidence of the signable bytes of the Lock.
 *
 * @generated from message co.topl.brambl.models.AccumulatorRootId
 */
export const AccumulatorRootId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.AccumulatorRootId",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * Represents the identifier of an TAM V2 group.
 * It is constructed using SHA-256 digest from fields label+fixedSeries+seriesTokenSupply+transactionId+utxoIndex.
 *
 * @generated from message co.topl.brambl.models.GroupId
 */
export const GroupId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.GroupId",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * Represents the identifier of an TAM V2 series.
 * It is constructed using SHA-256 digest from fields label+fixedSeries+seriesTokenSupply+transactionId+utxoIndex.
 *
 * @generated from message co.topl.brambl.models.SeriesId
 */
export const SeriesId = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.SeriesId",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

