// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/indices.proto (package co.topl.brambl.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message co.topl.brambl.models.Indices
 */
export const Indices = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.Indices",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "y", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "z", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

