// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/indices.proto (package co.topl.brambl.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message co.topl.brambl.models.Indices
 */
export declare class Indices extends Message<Indices> {
  /**
   * @generated from field: uint32 x = 1;
   */
  x: number;

  /**
   * @generated from field: uint32 y = 2;
   */
  y: number;

  /**
   * @generated from field: uint32 z = 3;
   */
  z: number;

  constructor(data?: PartialMessage<Indices>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.Indices";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Indices;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Indices;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Indices;

  static equals(a: Indices | PlainMessage<Indices> | undefined, b: Indices | PlainMessage<Indices> | undefined): boolean;
}

