// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file brambl/models/transaction/spent_transaction_output.proto (package co.topl.brambl.models.transaction, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { TransactionOutputAddress } from "../address_pb.js";
import { Attestation } from "../box/attestation_pb.js";
import { Value } from "../box/value_pb.js";

/**
 * Input to a transaction
 *
 * @generated from message co.topl.brambl.models.transaction.SpentTransactionOutput
 */
export class SpentTransactionOutput extends Message<SpentTransactionOutput> {
  /**
   * @generated from field: co.topl.brambl.models.TransactionOutputAddress address = 1;
   */
  address?: TransactionOutputAddress;

  /**
   * @generated from field: co.topl.brambl.models.box.Attestation attestation = 2;
   */
  attestation?: Attestation;

  /**
   * the value of the box being spent
   *
   * @generated from field: co.topl.brambl.models.box.Value value = 3;
   */
  value?: Value;

  constructor(data?: PartialMessage<SpentTransactionOutput>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "co.topl.brambl.models.transaction.SpentTransactionOutput";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "message", T: TransactionOutputAddress },
    { no: 2, name: "attestation", kind: "message", T: Attestation },
    { no: 3, name: "value", kind: "message", T: Value },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpentTransactionOutput {
    return new SpentTransactionOutput().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpentTransactionOutput {
    return new SpentTransactionOutput().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpentTransactionOutput {
    return new SpentTransactionOutput().fromJsonString(jsonString, options);
  }

  static equals(a: SpentTransactionOutput | PlainMessage<SpentTransactionOutput> | undefined, b: SpentTransactionOutput | PlainMessage<SpentTransactionOutput> | undefined): boolean {
    return proto3.util.equals(SpentTransactionOutput, a, b);
  }
}

