// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/transaction/unspent_transaction_output.proto (package co.topl.brambl.models.transaction, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { LockAddress } from "../address_pb.js";
import { Value } from "../box/value_pb.js";

/**
 * output of a transaction
 *
 * @generated from message co.topl.brambl.models.transaction.UnspentTransactionOutput
 */
export const UnspentTransactionOutput = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.transaction.UnspentTransactionOutput",
  () => [
    { no: 1, name: "address", kind: "message", T: LockAddress },
    { no: 2, name: "value", kind: "message", T: Value },
  ],
);

