// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/box/assets_statements.proto (package co.topl.brambl.models.box, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Struct, UInt32Value } from "@bufbuild/protobuf";
import { TransactionOutputAddress } from "../address_pb.js";
import { Int128 } from "../../../quivr/models/shared_pb.js";

/**
 * @generated from message co.topl.brambl.models.box.AssetMintingStatement
 */
export const AssetMintingStatement = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.AssetMintingStatement",
  () => [
    { no: 1, name: "groupTokenUtxo", kind: "message", T: TransactionOutputAddress },
    { no: 2, name: "seriesTokenUtxo", kind: "message", T: TransactionOutputAddress },
    { no: 3, name: "quantity", kind: "message", T: Int128 },
    { no: 4, name: "permanentMetadata", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message co.topl.brambl.models.box.AssetMergingStatement
 */
export const AssetMergingStatement = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.AssetMergingStatement",
  () => [
    { no: 1, name: "inputUtxos", kind: "message", T: TransactionOutputAddress, repeated: true },
    { no: 2, name: "outputIdx", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message co.topl.brambl.models.box.AssetSplittingStatement
 */
export const AssetSplittingStatement = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.AssetSplittingStatement",
  () => [
    { no: 1, name: "outputIndexes", kind: "message", T: UInt32Value, repeated: true },
    { no: 2, name: "inputUtxo", kind: "message", T: TransactionOutputAddress },
  ],
);

