// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/box/attestation.proto (package co.topl.brambl.models.box, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Lock_Commitment, Lock_Image, Lock_Predicate } from "./lock_pb.js";
import type { Proof } from "../../../quivr/models/proof_pb.js";
import type { Challenge } from "./challenge_pb.js";
import type { Witness } from "../../../quivr/models/shared_pb.js";

/**
 * encapsulates the lock and responses are used to satisfy locks (may be successful or unsuccessful)
 *
 * @generated from message co.topl.brambl.models.box.Attestation
 */
export declare class Attestation extends Message<Attestation> {
  /**
   * @generated from oneof co.topl.brambl.models.box.Attestation.value
   */
  value: {
    /**
     * @generated from field: co.topl.brambl.models.box.Attestation.Predicate predicate = 1;
     */
    value: Attestation_Predicate;
    case: "predicate";
  } | {
    /**
     * @generated from field: co.topl.brambl.models.box.Attestation.Image image = 2;
     */
    value: Attestation_Image;
    case: "image";
  } | {
    /**
     * @generated from field: co.topl.brambl.models.box.Attestation.Commitment commitment = 3;
     */
    value: Attestation_Commitment;
    case: "commitment";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Attestation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.box.Attestation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Attestation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Attestation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Attestation;

  static equals(a: Attestation | PlainMessage<Attestation> | undefined, b: Attestation | PlainMessage<Attestation> | undefined): boolean;
}

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Predicate
 */
export declare class Attestation_Predicate extends Message<Attestation_Predicate> {
  /**
   * @generated from field: co.topl.brambl.models.box.Lock.Predicate lock = 1;
   */
  lock?: Lock_Predicate;

  /**
   * list of optional values (proofs used to attempt to satisfy the challenges contained in the predicate lock)
   *
   * @generated from field: repeated quivr.models.Proof responses = 2;
   */
  responses: Proof[];

  constructor(data?: PartialMessage<Attestation_Predicate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.box.Attestation.Predicate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Attestation_Predicate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Attestation_Predicate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Attestation_Predicate;

  static equals(a: Attestation_Predicate | PlainMessage<Attestation_Predicate> | undefined, b: Attestation_Predicate | PlainMessage<Attestation_Predicate> | undefined): boolean;
}

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Image
 */
export declare class Attestation_Image extends Message<Attestation_Image> {
  /**
   * @generated from field: co.topl.brambl.models.box.Lock.Image lock = 1;
   */
  lock?: Lock_Image;

  /**
   * list of optional values
   *
   * @generated from field: repeated co.topl.brambl.models.box.Challenge known = 2;
   */
  known: Challenge[];

  /**
   * list of optional values
   *
   * @generated from field: repeated quivr.models.Proof responses = 3;
   */
  responses: Proof[];

  constructor(data?: PartialMessage<Attestation_Image>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.box.Attestation.Image";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Attestation_Image;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Attestation_Image;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Attestation_Image;

  static equals(a: Attestation_Image | PlainMessage<Attestation_Image> | undefined, b: Attestation_Image | PlainMessage<Attestation_Image> | undefined): boolean;
}

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Commitment
 */
export declare class Attestation_Commitment extends Message<Attestation_Commitment> {
  /**
   * @generated from field: co.topl.brambl.models.box.Lock.Commitment lock = 1;
   */
  lock?: Lock_Commitment;

  /**
   * list of claim propositions that must be proven as memebrs of the root commitment and be suitably satisfied by the given proofs
   *
   * @generated from field: repeated co.topl.brambl.models.box.Challenge known = 2;
   */
  known: Challenge[];

  /**
   * list of witnesses for proving membership of claimed propositions
   *
   * @generated from field: repeated quivr.models.Witness witness = 3;
   */
  witness: Witness[];

  /**
   * list of optional values
   *
   * @generated from field: repeated quivr.models.Proof responses = 4;
   */
  responses: Proof[];

  constructor(data?: PartialMessage<Attestation_Commitment>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "co.topl.brambl.models.box.Attestation.Commitment";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Attestation_Commitment;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Attestation_Commitment;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Attestation_Commitment;

  static equals(a: Attestation_Commitment | PlainMessage<Attestation_Commitment> | undefined, b: Attestation_Commitment | PlainMessage<Attestation_Commitment> | undefined): boolean;
}

