// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/box/attestation.proto (package co.topl.brambl.models.box, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Lock_Commitment, Lock_Image, Lock_Predicate } from "./lock_pb.js";
import { Proof } from "../../../quivr/models/proof_pb.js";
import { Challenge } from "./challenge_pb.js";
import { Witness } from "../../../quivr/models/shared_pb.js";

/**
 * encapsulates the lock and responses are used to satisfy locks (may be successful or unsuccessful)
 *
 * @generated from message co.topl.brambl.models.box.Attestation
 */
export const Attestation = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.Attestation",
  () => [
    { no: 1, name: "predicate", kind: "message", T: Attestation_Predicate, oneof: "value" },
    { no: 2, name: "image", kind: "message", T: Attestation_Image, oneof: "value" },
    { no: 3, name: "commitment", kind: "message", T: Attestation_Commitment, oneof: "value" },
  ],
);

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Predicate
 */
export const Attestation_Predicate = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.Attestation.Predicate",
  () => [
    { no: 1, name: "lock", kind: "message", T: Lock_Predicate },
    { no: 2, name: "responses", kind: "message", T: Proof, repeated: true },
  ],
  {localName: "Attestation_Predicate"},
);

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Image
 */
export const Attestation_Image = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.Attestation.Image",
  () => [
    { no: 1, name: "lock", kind: "message", T: Lock_Image },
    { no: 2, name: "known", kind: "message", T: Challenge, repeated: true },
    { no: 3, name: "responses", kind: "message", T: Proof, repeated: true },
  ],
  {localName: "Attestation_Image"},
);

/**
 * @generated from message co.topl.brambl.models.box.Attestation.Commitment
 */
export const Attestation_Commitment = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.Attestation.Commitment",
  () => [
    { no: 1, name: "lock", kind: "message", T: Lock_Commitment },
    { no: 2, name: "known", kind: "message", T: Challenge, repeated: true },
    { no: 3, name: "witness", kind: "message", T: Witness, repeated: true },
    { no: 4, name: "responses", kind: "message", T: Proof, repeated: true },
  ],
  {localName: "Attestation_Commitment"},
);

