// @generated by protoc-gen-es v1.8.0
// @generated from file brambl/models/box/box.proto (package co.topl.brambl.models.box, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Lock } from "./lock_pb.js";
import { Value } from "./value_pb.js";

/**
 * encapsulates a value and lock that is needed to be satisfied in order to unlock value
 *
 * @generated from message co.topl.brambl.models.box.Box
 */
export const Box = /*@__PURE__*/ proto3.makeMessageType(
  "co.topl.brambl.models.box.Box",
  () => [
    { no: 1, name: "lock", kind: "message", T: Lock },
    { no: 2, name: "value", kind: "message", T: Value },
  ],
);

